default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todoApi_development

test:
  <<: *default
  database: todoApi_test

production:
  <<: *default
  database: todoApi_production
  username: todoApi
  password: <%= ENV['TODOAPI_DATABASE_PASSWORD'] %>
